class QuizMasterError(Exception): ...
class FileNotSupportedError(QuizMasterError): ...
class ApiError(QuizMasterError): ...
class CardNotFoundError(QuizMasterError): ...
class StorageError(QuizMasterError): ...
